### ISSUE TITLE
Can't bypass this app

### ISSUE THREAD

**Issue by xiaotujinbnb** [AshenOneYe/FridaAntiRootDetection#1]
Can't bypass this app This is the download link
http://as.sogou.com/detail?pid=34&cid=42&docid=-1834933750158815209&e=1969

**Comment by AshenOneYe** [comment]
I tested this app, when I run it on a rooted device, it crashed soon.
so I modify the variable `target` to `com.sunboxsoft.charge.institute` in `antiroot.py` and run it by coding
`python antiroot.py`
after that I manually start the app it runs without crash.
I hope this will help you

**Comment by xiaotujinbnb** [comment]
I would like to ask why js crashes when running but not in python

**Comment by xiaotujinbnb** [comment]
The program has no crash log output normally, but the program is a white screen and cannot run normally

**Comment by AshenOneYe** [comment]
> 

Because this app uses multi-process to check whether the device has been rooted.
Directly using js with the command
`frida -U -f com.sunboxsoft.charge.institute -l antiroot.js --no-pause`
works in most cases.
But it only hook the main process that frida spawns.
So if the root checking operation happens in the child process,it won't work.
The py file only dose one thing, that is, enable child-gating to automatically hook all process whose name pass the filter immediately when it is spawned, so we can bypass the root check in all process.
